### PR TITLE
Signal simulation and segmentation

### PR DESCRIPTION
**Pull request by trailfog**
As part of our IP5 (Simulating the light from the big bang for the square kilometre array), the following work has been done:

Galactic Signal simulation
- Galactic Foreground
- Synchroton
- 21cm EoR signal

Segmentation-methods to extract the EoR signal:
- SegU-Net
- Superpixel

An example of how to use the new code is shown in the example iPython Notebook `karabo/examples/signal_simulation_segmentation.ipynb`

### CODE REVIEW

**Comment by Lukas113** [comment]
The overall code quality seems good. The only thing I have to complain about is that we want to support python >=3.9, but there are some 3.10 features in it. This needs to be changed.

To ensure that the changes are correct from a physical point of view, someone other than me must have a look at this, e.g. @rohitcbscient .

**Comment by trailfog** [comment]
@Lukas113, we developed the software using the Karabo env (python 3.9). However, I did find a 3.10 feature that slipped into the `typing.py` file:

```python
class SegmentationOutput(NamedTuple):
    """Output of the segmentation."""

    image: Image3D
    xhii_stitch: npt.NDArray[np.bool_] | None # => xhii_stitch: Optional[npt.NDArray[np.bool_]]
    mask_xhi: npt.NDArray[np.bool_]
    dt_smooth: npt.NDArray[np.float_]
    xhi_seg_err: npt.NDArray[np.float_] | None  # => xhi_seg_err: Optional[npt.NDArray[np.float_]]
```

Did you find anything else?

**Comment by trailfog** [comment]
@Lukas113 No problem. I just updated the offending lines.

**Comment by deiruch** [comment]
@rohitcbscient and @Lukas113 What do you think? Should/can we merge?

**Comment by deiruch** [comment]
Ok, so you approve? Let's wait for @rohitcbscient's opinion then.

**Review by rohitcbscient — APPROVED** [review]
The new signal for the simulation looks good.

**Pull request merged**
